title: CE 410/510 Theoretical and Computational Geomechanics
author: dianemoug
email: dmoug@pdx.edu
description: > # this means to ignore newlines until "baseurl:"
  This site provides tutorials for geotechnical modeling in FLAC 8.0
  The tutorials are formatted for you to work through homework assignments.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

# theme and formatting
theme: minima
